version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=063505748811.dkr.ecr.us-east-2.amazonaws.com/testing-repo-vinit-2
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker login -u AWS -p impetus22 063505748811.dkr.ecr.us-east-2.amazonaws.com
      - docker build -t 063505748811.dkr.ecr.us-east-2.amazonaws.com/testing-repo-vinit-2:latest .
      - docker tag 063505748811.dkr.ecr.us-east-2.amazonaws.com/testing-repo-vinit-2:latest 063505748811.dkr.ecr.us-east-2.amazonaws.com/testing-repo-vinit-2:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
